"""
NovaCure Platform — Auth Dependencies
Verifies Supabase JWTs generated by Supabase Auth and extracts user + role.
Used as FastAPI dependencies on every protected route.
"""

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import JWTError, jwt

import config
from database import get_admin_client, get_anon_client

security = HTTPBearer()

# ── Valid roles ───────────────────────────────────────────
VALID_ROLES = {"admin", "pharmacist", "warehouse_supervisor", "regional_manager"}

# ── Helpers ───────────────────────────────────────────────

def _decode_supabase_token(token: str) -> dict:
    """Verify the token natively with Supabase Auth to handle any Algorithm (HS256/ES256)."""
    try:
        anon = get_anon_client()
        user_resp = anon.auth.get_user(token)
        
        if not user_resp.user:
            raise HTTPException(status_code=401, detail="User not found")
            
        return {
            "sub": user_resp.user.id,
            "email": user_resp.user.email
        }
    except Exception as e:
        print(f"SUPABASE AUTH ERROR: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid or expired token: {e}",
        )


def _fetch_user_role(user_id: str) -> str | None:
    """Look up the user's role from the profiles table (service-role, bypasses RLS)."""
    client = get_admin_client()
    res = (
        client.table("profiles")
        .select("role")
        .eq("id", user_id)
        .maybe_single()
        .execute()
    )
    if res.data:
        return res.data.get("role")
    return None


# ── Main dependency: get_current_user ─────────────────────

async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
) -> dict:
    """
    Returns a dict with keys:
      - user_id  (str, UUID from Supabase auth.uid())
      - email    (str)
      - role     (str, from profiles table)
      - token    (str, raw JWT — pass to anon client if needed)
    """
    token = credentials.credentials
    print(f"RAW TOKEN RECEIVED: '{token}'")
    payload = _decode_supabase_token(token)

    user_id: str | None = payload.get("sub")
    email: str | None = payload.get("email")

    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token missing 'sub' claim",
        )

    # Fetch role from profiles table
    role = _fetch_user_role(user_id)
    if role is None:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User profile not found. Please complete registration.",
        )

    return {
        "user_id": user_id,
        "email": email or "",
        "role": role,
        "token": token,
    }


# ── Role-based guards ────────────────────────────────────

def require_role(*allowed_roles: str):
    """
    Factory that returns a dependency requiring the user to have one of the
    specified roles.

    Usage:
        @router.get("/admin-only", dependencies=[Depends(require_role("admin"))])
    """
    async def _guard(current_user: dict = Depends(get_current_user)) -> dict:
        if current_user["role"] not in allowed_roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Role '{current_user['role']}' not authorized. Requires one of: {allowed_roles}",
            )
        return current_user
    return _guard


# ── Convenience shortcuts ─────────────────────────────────

require_admin = require_role("admin")
require_pharmacist = require_role("pharmacist", "admin")
require_warehouse = require_role("warehouse_supervisor", "admin")
require_manager = require_role("regional_manager", "admin")
